# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:41
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'option1'), (2, 'option2'), (3, 'option3'), (4, 'option4')], max_length=7),
        ),
    ]
