# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20170621_0741'),
        ('teacher', '0004_auto_20170621_1003'),
    ]

    operations = [
    ]
