# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20170621_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks_per_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
