# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20170711_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
