# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='question',
            name='timestamp',
        ),
    ]
