# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20170711_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='negative_marks',
            field=models.IntegerField(default=0),
        ),
    ]
