# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_auto_20170621_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Exam')),
                ('Test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Question')),
            ],
        ),
    ]
