# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20170621_0741'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='Test_question',
        ),
    ]
