# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170704_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
